#!/bin/python3

import sys


arr = []
for arr_i in range(6):
   arr_t = [int(arr_temp) for arr_temp in input().strip().split(' ')]
   arr.append(arr_t)

#print(arr)

def HourGlassSum(y,x,A):
    
    # First check that a valid coordinate is given.
    # In otherwords, check that the center isn't on an edge.
    # Entries on the edge don't have hourglass sums.*
    # *Assuming the definiton above.
    
    if (x == 0) or (x == 5) or (y == 0) or (y == 5):
        print("Invalid coordinate given! Edge elements have undefined hourglass sums!")
        exit
    hourglassSum = A[x][y] + A[x+1][y+1] + A[x-1][y+1] + A[x-1][y] + A[x-1][y-1] + A[x+1][y-1] + A[x+1][y]            
    
    return hourglassSum

def FindMaxHourGlassSum(A):
    
    hourglassSums = []
    
    for x in range(1,5):
        for y in range(1,5):
            hourglassSums.append(HourGlassSum(x,y,A))
            
    print(max(hourglassSums))
    #print(hourglassSums)

FindMaxHourGlassSum(arr)
#print(HourGlassSum(1,1,arr))
